### ISSUE TITLE
HTML validator

### ISSUE THREAD

**Issue by TessaViergever** [Patrickkhr/your-tribe-profile-card#2]
Handige link om je HTML te valideren:

https://validator.w3.org/

**Comment by Patrickkhr** [comment]
Bedankt voor de tip. Ik de errors in mijn code opgelost!
<img width="838" alt="image" src="https://github.com/Patrickkhr/your-tribe-profile-card/assets/143999685/13880723-eda1-40bd-b367-45e7415d60d8">
