### ISSUE TITLE
Alt tag in <img>

### ISSUE THREAD

**Issue by TessaViergever** [Patrickkhr/your-tribe-profile-card#3]
https://github.com/Patrickkhr/your-tribe-profile-card/blob/105f29c31cda5426dcbade4b5dbbc49638b44c33/index.html#L23

Een <img> heeft een alt tag nodig. Als de afbeelding niet laadt of als iemand slecht ziend is, zie je de omschrijving van wat er op de afbeelding te zien is of kan een screenreader oplezen wat er op de img staat.

**Comment by Patrickkhr** [comment]
Ik heb de alt tag toegevoegd aan de <img>.

https://github.com/Patrickkhr/your-tribe-profile-card/blob/1417efe10a2dcd7c1c1603946c34c57439e3f57d/index.html#L23
